package flca.blazeds.template;


public enum TidBlazeDs {

	ALL_FILES,
	PROTOBUF ,
	PROTOBUF_MSG,
	MAPPER ,
	MOCK_DART,
	MOCK_JAVA_GRPC,  //mockdata for Java classes generated by grpc
	MOCK_JAVA, // mockdata for original Java classes.
	TEST_MAPPER,
	OPEN_API_YAML,
	SWAGGER,
}
